version: "2.1"

dependencies: ./project-dependencies.yaml

default:
  build-command:
    current: |
      echo $(ls -l ~/.m2/repository/com/mycompany/app/)
      mvn -e clean install
    upstream: |
      echo $(ls -l ~/.m2/repository/com/mycompany/app/)
      mvn -e -T1C clean install -DskipTests
    after:
      upstream: rm -rf ./*
