version: "2.1"

dependencies: ./project-dependencies.yaml

default:
  build-command:
    before:
      current: ls -l ~/.m2/repository/
      upstream: ls -l ~/.m2/repository/
    current: |
      mvn -e clean install
    upstream: |
      mvn -e -T1C clean install -DskipTests
    after:
      upstream: rm -rf ./*
